name: Deploy to Cloud Run

on:
  workflow_dispatch:  # ✅ allows manual trigger

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Directory
        run: ls -al

      # 2️⃣ Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: linkifyurl
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LINKIFYURL }}
          export_default_credentials: true

      # 3️⃣ Build and push Docker image
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/linkifyurl/innkie-backend

      - name: Check Directory
        run: ls -al

      # 4️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy innkie-backend \
            --image gcr.io/linkifyurl/innkie-backend \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account firebase-adminsdk-fbsvc@linkifyurl.iam.gserviceaccount.com
